let dataBlog = [
  {
    id: 1,
    title:
      "Mengenal PPG Prajabatan: Jalan Menuju Guru Profesional di Indonesia",
    slug: "mengenal-ppg-prajabatan-jalan-menuju-guru-profesional-di-indonesia",
    tag: ["Pendidikan", "PPG Prajabatan", "Calon Guru", "Karir"],
    created_at: "14 Juni 2026",
    updated_at: "17 Juni 2026",
    thumbnail: "ppg-prajabatan.webp",
    body: "<h2 style='text-align: justify;'>Apa Itu PPG Prajabatan?</h2><p class='isSelectedEnd' style='text-align: justify;'>Pendidikan Profesi Guru (PPG) Prajabatan merupakan program pendidikan profesi yang diselenggarakan pemerintah untuk mempersiapkan calon guru profesional sebelum terjun ke dunia pendidikan. Program ini ditujukan bagi lulusan Sarjana (S1), Sarjana Terapan (D4), baik dari jurusan kependidikan maupun non-kependidikan, yang memiliki minat dan panggilan untuk menjadi guru. Program ini memberikan kesempatan kepada para calon pendidik untuk memperoleh sertifikat pendidik sebagai salah satu syarat menjadi guru profesional di Indonesia.</p><p class='isSelectedEnd' style='text-align: justify;'>PPG Prajabatan hadir sebagai bagian dari upaya peningkatan kualitas pendidikan nasional melalui penyediaan guru-guru yang kompeten, berintegritas, dan mampu menjawab tantangan pendidikan abad ke-21. Melalui program ini, calon guru tidak hanya memperoleh pengetahuan teoritis, tetapi juga pengalaman praktik mengajar secara langsung di sekolah.</p><h2 style='text-align: justify;'>Mengapa PPG Prajabatan Penting?</h2><p class='isSelectedEnd' style='text-align: justify;'>Guru merupakan salah satu profesi yang memiliki peran strategis dalam pembangunan bangsa. Oleh karena itu, menjadi guru tidak cukup hanya dengan memiliki gelar sarjana. Seorang guru juga harus memiliki kompetensi pedagogik, profesional, sosial, dan kepribadian yang diperoleh melalui pendidikan profesi. PPG Prajabatan dirancang untuk memastikan bahwa calon guru memiliki kemampuan tersebut sebelum memasuki dunia kerja.</p><p class='isSelectedEnd' style='text-align: justify;'>Selain itu, perkembangan teknologi, perubahan karakteristik peserta didik, serta tuntutan pembelajaran yang semakin kompleks mengharuskan guru memiliki kemampuan adaptasi yang tinggi. PPG Prajabatan menjadi wadah bagi calon guru untuk mengembangkan kompetensi tersebut secara sistematis.</p><h2 style='text-align: justify;'>Tujuan PPG Prajabatan</h2><p class='isSelectedEnd' style='text-align: justify;'>Secara umum, tujuan PPG Prajabatan adalah menghasilkan guru profesional yang:</p><ul style='text-align: justify;' data-spread='false'><li>Memiliki kompetensi pedagogik yang kuat.</li><li>Mampu merancang dan melaksanakan pembelajaran yang berpusat pada peserta didik.</li><li>Menjadi teladan dalam sikap dan perilaku.</li><li>Memiliki jiwa kepemimpinan dan kemampuan berkolaborasi.</li><li>Adaptif terhadap perkembangan teknologi dan inovasi pendidikan.</li><li>Menjadi pembelajar sepanjang hayat.</li></ul><p class='isSelectedEnd' style='text-align: justify;'>Melalui program ini, pemerintah berharap tercipta generasi baru guru Indonesia yang mampu mendukung terwujudnya Profil Pelajar Pancasila.</p><h2 style='text-align: justify;'>Struktur dan Kegiatan PPG Prajabatan</h2><p class='isSelectedEnd' style='text-align: justify;'>Program PPG Prajabatan umumnya ditempuh selama dua semester. Selama mengikuti program, mahasiswa akan menjalani berbagai kegiatan pembelajaran yang berorientasi pada praktik, antara lain:</p><h3 style='text-align: justify;'>1. Perkuliahan Berorientasi Praktik</h3><p class='isSelectedEnd' style='text-align: justify;'>Mahasiswa mempelajari berbagai mata kuliah yang berkaitan dengan filosofi pendidikan, karakteristik peserta didik, strategi pembelajaran, asesmen, pembelajaran sosial emosional, hingga teknologi pendidikan.</p><h3 style='text-align: justify;'>2. Praktik Pengalaman Lapangan (PPL)</h3><p class='isSelectedEnd' style='text-align: justify;'>Mahasiswa ditempatkan di sekolah untuk melakukan observasi, membantu proses pembelajaran, hingga mengajar secara mandiri dengan bimbingan guru pamong dan dosen pembimbing. Kegiatan ini menjadi sarana untuk mengaplikasikan teori yang telah dipelajari di perkuliahan.</p><h3 style='text-align: justify;'>3. Proyek Kepemimpinan</h3><p class='isSelectedEnd' style='text-align: justify;'>Selain mengajar, mahasiswa juga diberikan kesempatan untuk merancang dan melaksanakan proyek yang memberikan dampak positif bagi sekolah maupun masyarakat sekitar.</p><h3 style='text-align: justify;'>4. Pendampingan dan Refleksi</h3><p class='isSelectedEnd' style='text-align: justify;'>Sepanjang program, mahasiswa memperoleh pendampingan intensif dari dosen dan guru pamong untuk mengembangkan kompetensi profesional serta melakukan refleksi terhadap praktik pembelajaran yang telah dilakukan.</p><h2 style='text-align: justify;'>Siapa yang Bisa Mengikuti PPG Prajabatan?</h2><p class='isSelectedEnd' style='text-align: justify;'>PPG Prajabatan terbuka bagi:</p><ul style='text-align: justify;' data-spread='false'><li>Warga Negara Indonesia (WNI).</li><li>Lulusan S1 atau D4 yang terdaftar di PD-Dikti.</li><li>Lulusan program studi kependidikan maupun non-kependidikan yang sesuai dengan bidang studi yang dibutuhkan.</li><li>Memenuhi persyaratan administrasi dan seleksi yang ditetapkan pemerintah.</li></ul><p class='isSelectedEnd' style='text-align: justify;'>Dengan demikian, peluang menjadi guru profesional tidak hanya terbuka bagi lulusan fakultas pendidikan, tetapi juga lulusan dari berbagai disiplin ilmu lainnya yang memiliki minat untuk mengajar.</p><h2 style='text-align: justify;'>Tantangan Menjalani PPG Prajabatan</h2><p class='isSelectedEnd' style='text-align: justify;'>Meskipun menawarkan banyak manfaat, PPG Prajabatan juga memiliki tantangan tersendiri. Peserta harus mampu mengelola waktu antara perkuliahan, tugas akademik, praktik mengajar, serta proyek kepemimpinan. Selain itu, proses seleksi yang kompetitif menuntut calon peserta untuk mempersiapkan diri dengan baik.</p><p class='isSelectedEnd' style='text-align: justify;'>Namun demikian, tantangan tersebut merupakan bagian dari proses pembentukan karakter dan profesionalisme calon guru yang akan bertugas mendidik generasi penerus bangsa.</p><h2 style='text-align: justify;'>Peluang Setelah Lulus PPG Prajabatan</h2><p class='isSelectedEnd' style='text-align: justify;'>Lulusan PPG Prajabatan akan memperoleh sertifikat pendidik yang menjadi bukti kompetensi profesional sebagai guru. Sertifikat ini dapat menjadi modal penting untuk berkarier di dunia pendidikan, baik di sekolah negeri maupun swasta sesuai ketentuan yang berlaku.</p><p class='isSelectedEnd' style='text-align: justify;'>Selain itu, lulusan PPG diharapkan mampu menjadi agen perubahan yang menghadirkan pembelajaran berkualitas, inovatif, dan berorientasi pada kebutuhan peserta didik.</p><h2 style='text-align: justify;'>Penutup</h2><p class='isSelectedEnd' style='text-align: justify;'>PPG Prajabatan merupakan langkah penting dalam mencetak guru-guru profesional yang siap menghadapi tantangan pendidikan masa kini dan masa depan. Melalui kombinasi antara teori, praktik lapangan, proyek kepemimpinan, dan pendampingan, program ini memberikan pengalaman belajar yang komprehensif bagi calon pendidik.</p><p style='text-align: justify;'>Bagi Anda yang memiliki cita-cita menjadi guru profesional dan ingin berkontribusi dalam meningkatkan kualitas pendidikan Indonesia, PPG Prajabatan dapat menjadi pilihan yang tepat untuk memulai perjalanan tersebut. Menjadi guru bukan hanya tentang mengajar, tetapi juga tentang membentuk karakter, menginspirasi, dan menciptakan masa depan yang lebih baik bagi generasi bangsa.</p>",
    excerpt:
      "Pendidikan Profesi Guru (PPG) Prajabatan merupakan program pendidikan profesi yang diselenggarakan pemerintah untuk mempersiapkan calon guru profesional sebelum terjun ke dunia pendidikan",
  },
  {
    id: 2,
    title: "Peran Guru dalam Era Digital",
    slug: "peran-guru-dalam-era-digital",
    tag: ["Pendidikan", "Teknologi"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "2.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "Guru kini berperan sebagai fasilitator pembelajaran yang membantu siswa memanfaatkan teknologi secara bijak dan produktif.",
  },
  {
    id: 3,
    title: "Meningkatkan Motivasi Belajar Siswa",
    slug: "meningkatkan-motivasi-belajar-siswa",
    tag: ["Pendidikan", "Tips"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "3.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "Motivasi belajar dapat ditingkatkan melalui strategi pembelajaran yang menarik, interaktif, dan sesuai kebutuhan siswa.",
  },
  {
    id: 4,
    title: "Pentingnya Literasi Digital bagi Pelajar",
    slug: "pentingnya-literasi-digital-bagi-pelajar",
    tag: ["Pendidikan", "Literasi"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "4.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "Literasi digital membantu pelajar memahami, mengevaluasi, dan memanfaatkan informasi dari internet secara bertanggung jawab.",
  },
  {
    id: 5,
    title: "Pengalaman Mengajar Saat PPL",
    slug: "pengalaman-mengajar-saat-ppl",
    tag: ["PPL", "Pengalaman"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "5.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "Pengalaman PPL memberikan banyak pelajaran berharga tentang praktik mengajar, manajemen kelas, dan interaksi dengan siswa.",
  },
  {
    id: 6,
    title: "Mengenal Kurikulum Merdeka",
    slug: "mengenal-kurikulum-merdeka",
    tag: ["Pendidikan", "Kurikulum"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "6.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "Kurikulum Merdeka memberikan fleksibilitas bagi guru dan siswa untuk menciptakan pembelajaran yang lebih bermakna.",
  },
  {
    id: 7,
    title: "Belajar JavaScript untuk Pemula",
    slug: "belajar-javascript-untuk-pemula",
    tag: ["Pemrograman", "JavaScript"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "7.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "JavaScript merupakan bahasa pemrograman yang penting untuk membuat website menjadi lebih interaktif dan dinamis.",
  },
  {
    id: 8,
    title: "Dasar-Dasar HTML dan CSS",
    slug: "dasar-dasar-html-dan-css",
    tag: ["Web Development", "HTML"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "8.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "HTML dan CSS adalah fondasi utama dalam pengembangan website yang perlu dikuasai oleh setiap web developer.",
  },
  {
    id: 9,
    title: "Tips Menjadi Guru yang Inspiratif",
    slug: "tips-menjadi-guru-yang-inspiratif",
    tag: ["Pendidikan", "Motivasi"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "9.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "Guru inspiratif mampu membangun semangat belajar siswa melalui keteladanan, kreativitas, dan komunikasi yang baik.",
  },
  {
    id: 10,
    title: "Pemanfaatan AI dalam Dunia Pendidikan",
    slug: "pemanfaatan-ai-dalam-dunia-pendidikan",
    tag: ["AI", "Pendidikan"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "10.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "Kecerdasan buatan dapat membantu proses pembelajaran melalui personalisasi materi, evaluasi, dan pembuatan konten edukatif.",
  },
];

let dataTagBlog = [
  "Pendidikan",
  "Opini",
  "Teknologi",
  "Tips",
  "Literasi",
  "PPG Prajabatan",
  "Pengalaman",
  "Kurikulum",
  "Pemrograman",
  "JavaScript",
  "Web Development",
  "HTML",
  "Motivasi",
  "AI",
];
