let dataBlog = [
  {
    id: 1,
    title: "Dinamika Pendidikan di Indonesia",
    slug: "dinamika-pendidikan-di-indonesia",
    tag: ["Pendidikan", "Opini"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "1.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "Pendidikan di Indonesia terus berkembang melalui berbagai kebijakan dan inovasi untuk meningkatkan kualitas pembelajaran.",
  },
  {
    id: 2,
    title: "Peran Guru dalam Era Digital",
    slug: "peran-guru-dalam-era-digital",
    tag: ["Pendidikan", "Teknologi"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "2.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "Guru kini berperan sebagai fasilitator pembelajaran yang membantu siswa memanfaatkan teknologi secara bijak dan produktif.",
  },
  {
    id: 3,
    title: "Meningkatkan Motivasi Belajar Siswa",
    slug: "meningkatkan-motivasi-belajar-siswa",
    tag: ["Pendidikan", "Tips"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "3.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "Motivasi belajar dapat ditingkatkan melalui strategi pembelajaran yang menarik, interaktif, dan sesuai kebutuhan siswa.",
  },
  {
    id: 4,
    title: "Pentingnya Literasi Digital bagi Pelajar",
    slug: "pentingnya-literasi-digital-bagi-pelajar",
    tag: ["Pendidikan", "Literasi"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "4.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "Literasi digital membantu pelajar memahami, mengevaluasi, dan memanfaatkan informasi dari internet secara bertanggung jawab.",
  },
  {
    id: 5,
    title: "Pengalaman Mengajar Saat PPL",
    slug: "pengalaman-mengajar-saat-ppl",
    tag: ["PPL", "Pengalaman"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "5.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "Pengalaman PPL memberikan banyak pelajaran berharga tentang praktik mengajar, manajemen kelas, dan interaksi dengan siswa.",
  },
  {
    id: 6,
    title: "Mengenal Kurikulum Merdeka",
    slug: "mengenal-kurikulum-merdeka",
    tag: ["Pendidikan", "Kurikulum"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "6.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "Kurikulum Merdeka memberikan fleksibilitas bagi guru dan siswa untuk menciptakan pembelajaran yang lebih bermakna.",
  },
  {
    id: 7,
    title: "Belajar JavaScript untuk Pemula",
    slug: "belajar-javascript-untuk-pemula",
    tag: ["Pemrograman", "JavaScript"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "7.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "JavaScript merupakan bahasa pemrograman yang penting untuk membuat website menjadi lebih interaktif dan dinamis.",
  },
  {
    id: 8,
    title: "Dasar-Dasar HTML dan CSS",
    slug: "dasar-dasar-html-dan-css",
    tag: ["Web Development", "HTML"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "8.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "HTML dan CSS adalah fondasi utama dalam pengembangan website yang perlu dikuasai oleh setiap web developer.",
  },
  {
    id: 9,
    title: "Tips Menjadi Guru yang Inspiratif",
    slug: "tips-menjadi-guru-yang-inspiratif",
    tag: ["Pendidikan", "Motivasi"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "9.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "Guru inspiratif mampu membangun semangat belajar siswa melalui keteladanan, kreativitas, dan komunikasi yang baik.",
  },
  {
    id: 10,
    title: "Pemanfaatan AI dalam Dunia Pendidikan",
    slug: "pemanfaatan-ai-dalam-dunia-pendidikan",
    tag: ["AI", "Pendidikan"],
    created_at: "14 Juni 2026",
    updated_at: "14 Juni 2026",
    thumbnail: "10.png",
    body: "<p style='text-align: justify;'>Artikel ini merupakan artikel contoh yang digunakan untuk kebutuhan demonstrasitampilan dan pengembangan fitur pada halaman blog. Seluruh isi tulisan,gambar, maupun informasi yang ditampilkan di dalam artikel ini dibuat sebagaidata dummy dan tidak dimaksudkan sebagai sumber informasi yang sebenarnya.</p><p style='text-align: justify;'>Tujuan dari artikel contoh ini adalah untuk membantu proses pengujian desain,tata letak, navigasi, pencarian, pagination, serta berbagai fitur lain yangberkaitan dengan sistem blog. Dengan adanya konten contoh, pengembang dapatmelihat bagaimana artikel akan ditampilkan kepada pengunjung ketika websitesudah digunakan secara penuh.</p><p style='text-align: justify;'>Apabila website ini nantinya dipublikasikan, artikel contoh seperti ini dapatdigantikan dengan konten asli yang sesuai dengan tema blog, seperti pendidikan,teknologi, pengalaman mengajar, pengembangan web, maupun topik lainnya.Terima kasih telah mengunjungi halaman ini dan semoga contoh artikel ini dapatmembantu dalam proses pengembangan website.</p>",
    excerpt:
      "Kecerdasan buatan dapat membantu proses pembelajaran melalui personalisasi materi, evaluasi, dan pembuatan konten edukatif.",
  },
];

let dataTagBlog = [
  "Pendidikan",
  "Opini",
  "Teknologi",
  "Tips",
  "Literasi",
  "PPL",
  "Pengalaman",
  "Kurikulum",
  "Pemrograman",
  "JavaScript",
  "Web Development",
  "HTML",
  "Motivasi",
  "AI",
];
